---
- name: configure all setup
  hosts: local
  become: true

  tasks:

    name: instalar paquetes requeridos
    apt:
      name:
        - xorriso
        - isolinux
        - syslinux-utils
        - rsync
        - whois
      state: present

    name: crear sha-512
    ansible.builtin.command: mkpasswd -m sha-512 'password'   
    
    name: prepare treee working
    