#SPDX-License-Identifier: MIT-0
---
# Detectar usuario actual automáticamente
user: "{{ lookup('env', 'USER') }}"

# Path adaptable al usuario actual
path_ssh_user: "/home/{{ lookup('env', 'USER') }}/.ssh/authorized_keys"

url_iso: https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-13.1.0-amd64-netinst.iso
name_virtual: virtualbox-6.1_6.1.50-161033~Ubuntu~jammy_amd64.deb
virtualbox_url: https://download.virtualbox.org/virtualbox/6.1.50/{{ name_virtual }}
# vars file for vms_iso_role
