---
# ============================================
# PLAYBOOK 1: CREAR VMS (localhost)
<<<<<<< HEAD
# ============================================
=======

# # ============================================

>>>>>>> 83ef055b087d9b3501e50b263b703320aadbeae2
# - name: Crear infraestructura de VMs
#   hosts: host
#   become: yes
#   roles:
#     - vms_iso_role  # Descomentar para crear ISO personalizada
#     - vm-role       # Descomentar para crear las VMs

# ============================================
# PLAYBOOK 2: CONFIGURAR /etc/hosts
# ============================================
- name: Configurar /etc/hosts en todos los nodos
  hosts: master,worker
  become: yes
  tasks:
    - name: Agregar master a /etc/hosts
      lineinfile:
        path: /etc/hosts
<<<<<<< HEAD
        line: "192.168.1.21 k8s-master"
=======
        line: "192.168.1.100 k8s-master"
>>>>>>> 83ef055b087d9b3501e50b263b703320aadbeae2
        state: present

    - name: Agregar worker a /etc/hosts
      lineinfile:
        path: /etc/hosts
<<<<<<< HEAD
        line: "192.168.1.22 k8s-worker"
=======
        line: "192.168.1.101 k8s-worker"
>>>>>>> 83ef055b087d9b3501e50b263b703320aadbeae2
        state: present

    - name: Configurar hostname propio
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

# ============================================
# PLAYBOOK 3: INSTALAR MICROK8S EN MASTER
# ============================================
- name: Instalar y configurar MicroK8s en Master
  hosts: master
  become: yes
  roles:
    - microk8s

# ============================================
# PLAYBOOK 4: INSTALAR MICROK8S EN WORKER
# ============================================
- name: Instalar y configurar MicroK8s en Worker
  hosts: worker
  become: yes
  roles:
    - microk8s