---
# ============================================
# PLAYBOOK 1: CREAR VMS (localhost)
# ============================================
# - name: Crear infraestructura de VMs
#   hosts: host
#   become: yes
#   roles:
#     - vms_iso_role  # Descomentar para crear ISO personalizada
#     - vm-role       # Descomentar para crear las VMs


- name: configurar hostname
  hosts: master,worker
  become: yes
  tasks:
    - name: Configurar hostname propio
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

# ============================================
# PLAYBOOK 2: CONFIGURAR /etc/hosts
# ============================================
- name: Configurar /etc/hosts en todos los nodos
  hosts: master,worker
  become: yes
  tasks:
    - name: Agregar master a /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "192.168.1.15 k8s-master"
        state: present

    - name: Agregar worker a /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "192.168.1.16 k8s-worker"
        state: present

# ============================================
# PLAYBOOK 3: INSTALAR MICROK8S EN MASTER
# ============================================
- name: Instalar y configurar MicroK8s en Master
  hosts: master
  become: yes
  roles:
    - microk8s

# ============================================
# PLAYBOOK 4: INSTALAR MICROK8S EN WORKER
# ============================================
- name: Instalar y configurar MicroK8s en Worker
  hosts: worker
  become: yes
  roles:
    - microk8s

# ============================================
# PLAYBOOK 5: INSTALAR DOCKER EN TOOLS
# ============================================

- name: Instalar Docker en herramienta
  hosts: tools
  become: yes
  roles:
    - docker

# ============================================
# PLAYBOOK 5: INSTALAR VAULT EN TOOLS
# ============================================

- name: Instalar VAULT en tools
  hosts: tools
  become: yes
  roles:
    - vault