---
- name: Crear los directorios 
  file:
    path: "{{ path_iso }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ MNT_DIR }}"
    - "{{ WRK_DIR }}"

- name: Copiar la iso en la ruta iso
  copy:
    src: "{{path_iso_download}}"
    dest: "{{ SRC_ISO }}"
    mode: '0644'

- name: Montar la iso
  mount:
    path: "{{ MNT_DIR }}"
    src: "{{ SRC_ISO }}"
    fstype: iso9660
    opts: loop
    state: mounted

- name: "[OPTIMIZADO] Sincronizar contenido del ISO (rsync en modo espejo)"
  command:
    cmd: "rsync -a --delete {{ MNT_DIR }}/ {{ WRK_DIR }}/"
  args:
    creates: "{{ WRK_DIR }}/dists"  # ¡Condición de idempotencia!
  become: yes
  changed_when: false