---
- name: Instalar y configurar nginx
  hosts: host
  become: yes
  tasks:

  - name: instalar el paquete de nginx
    apt: # modulo de ansible para descargar por apt
      name: "{{ web_server_package }}"
      state: present

  - name: Copiar configuracion
    template: # Modulo integrado de ansible para copiar
      src: ./files/nginx-config.j2
      dest: /etc/nginx/sites-available/default
    notify: # OJITO ESTA ES LA QUE LE AVISA AL HANDLER PA QUE ESTE PENDIENTE
      - Reiniciar Ngnix

  - name: Copiar nuestra pagina
    copy:
      src: ./files/index.html
      dest: "{{ document_root }}/index.html"

  - name: ASEGURAR
    service: # modulo que controla los servicio de los host
      name: "{{web_server_service}}"
      state: started
      enabled: yes   

  handlers:
    - name: Reiniciar Ngnix
      service:
        name: "{{web_server_service}}"
        state: restarted